import numpy as np
from find_V_and_phi_tag_tag import V_fun, phi_tag_tag_fun
from blur_func import gaussian_blur2d

# ---------------------- Pipeline ----------------------

def initial_processing(
    I1,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Compute the log-intensity difference and cosine double-angle map.
    If I2 is None and sigma is provided, I2 is generated by convolving I1 with
    a 2D Gaussian (μ=0, σ=sigma along x & y).

    IMPORTANT:
    We only take ln(I1/I2) where I1/I2 > 0. Invalid points are set to NaN
    so they can be masked out upstream.
    """
    # I1   : numpy array -> Intensity map I1
    # chi  : numpy array -> Angle map in radians (same shape as I1)
    # I2   : numpy array or None -> Optional intensity map I2
    # sigma: float or None -> std for Gaussian-blur to generate I2 when I2 is None

    if I2 is None and sigma is None:
        raise ValueError("Provide either I2 or sigma to generate I2 via Gaussian blur.")
    if I2 is not None and sigma is not None:
        raise ValueError("Provide exactly one of I2 or sigma, not both.")

    if sigma is not None:
        I2 = gaussian_blur2d(I1, float(sigma))

    if I1.shape != I2.shape or I1.shape != chi.shape:
        raise ValueError("I1, I2, and chi must have identical shapes.")

    # Mask where the ratio is valid and finite
    with np.errstate(divide='ignore', invalid='ignore'):
        ratio = I1 / I2
    valid_ratio = np.isfinite(ratio) & (ratio > 0)

    ln_delta_I = np.full_like(I1, np.nan, dtype=float)
    ln_delta_I[valid_ratio] = np.log(ratio[valid_ratio])

    cos_2_chi = np.cos(2 * chi)
    return ln_delta_I, cos_2_chi


def get_m_and_g_constants(
    I1,
    q,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Global linear least-squares fit over ALL valid samples:
      y = G(q) + M(q) * x

    with t = q**2 and polynomial bases:
      G(q) = g0 + g1*t + g2*t**2 + g3*t**3
      M(q) = m1*t + m2*t**2 + m3*t**3

    Optional:
      Provide I2 directly OR provide sigma to generate I2 = GaussianBlur(I1, sigma).

    Returns ALL coefficients:
      g0, g1, g2, g3, m1, m2, m3
    """
    # I1 : numpy array -> Intensity map I1
    # q  : numpy array -> Radial q (same shape as I1)
    # chi: numpy array -> Angle chi (same shape as I1)
    # I2 : numpy array or None -> Optional intensity map I2
    # sigma : float or None -> Gaussian sigma when I2 is None

    if I1.shape != q.shape or I1.shape != chi.shape:
        raise ValueError("I1, q, and chi must have identical shapes.")

    ln_delta_I, cos_2_chi = initial_processing(I1, chi, I2=I2, sigma=sigma)

    # Build flattened arrays and mask out invalids:
    y = ln_delta_I.ravel()
    x = cos_2_chi.ravel()
    t = (q**2).ravel()

    valid = np.isfinite(y) & np.isfinite(x) & np.isfinite(t)
    y = y[valid]; x = x[valid]; t = t[valid]

    # If nothing valid, fail clearly
    if y.size == 0:
        raise ValueError("No valid samples where I1/I2 > 0 to perform the fit.")

    # Design matrix columns: [1, t, t^2, t^3, x*t, x*t^2, x*t^3]
    Phi_g = np.column_stack([np.ones_like(t), t, t**2, t**3])
    Phi_m = np.column_stack([t, t**2, t**3])
    Z = np.column_stack([Phi_g, x[:, None] * Phi_m])

    theta, _, _, _ = np.linalg.lstsq(Z, y, rcond=None)
    g0, g1, g2, g3, m1, m2, m3 = theta
    return (float(g0), float(g1), float(g2), float(g3),
            float(m1), float(m2), float(m3))


def get_V_and_phi_tagtag(
    I1,
    q,
    chi,
    *,
    r_g_sq_mod,
    I2=None,
    sigma=None
):
    """
    Compute (V, phi_tagtag) via polynomial maps over (c_g, c_m).

    Options (mutually exclusive):
      - Provide I2 directly (2D numpy array).
      - OR provide sigma (float): generates I2 = GaussianBlur(I1, sigma).
    """
    # I1         : numpy array -> Intensity map I1
    # q          : numpy array -> Radial q
    # chi        : numpy array -> Angle chi
    # r_g_sq_mod : float       -> Modified radius of gyration squared (positive)
    # I2         : numpy array or None
    # sigma      : float or None

    if r_g_sq_mod <= 0:
        raise ValueError("r_g_sq_mod must be positive.")
    if (I2 is None) == (sigma is None):
        raise ValueError("Provide exactly one of I2 or sigma.")

    # Fit coefficients (handles I2 generation & masking internally)
    g0, g1, g2, g3, m1, m2, m3 = get_m_and_g_constants(I1, q, chi, I2=I2, sigma=sigma)

    # Use the right coefficients for c_g and c_m
    c_g = g1 / (g0 * r_g_sq_mod)
    c_m = m2 / (m1 * r_g_sq_mod)

    V = V_fun(c_m, c_g)
    phi = phi_tag_tag_fun(c_m, c_g)

    return [(float(V), float(phi))]