import numpy as np
from find_V_and_phi_tag_tag import V_fun, phi_tag_tag_fun


# ---------- Gaussian blur helpers (separable, no SciPy) ----------

def _gaussian_kernel1d(sigma, truncate=3.0):
    """
    Build a 1D Gaussian kernel with mean 0 and std=sigma.
    Kernel length = 2*ceil(truncate*sigma)+1, normalized to sum=1.
    """
    # sigma : float -> standard deviation (pixels)
    if sigma <= 0:
        raise ValueError("sigma must be positive.")
    radius = int(np.ceil(truncate * sigma))
    x = np.arange(-radius, radius + 1, dtype=float)
    k = np.exp(-0.5 * (x / sigma) ** 2)
    k /= k.sum()
    return k


def _convolve1d_reflect(arr, kernel, axis):
    """
    Separable 1D convolution along one axis with 'reflect' padding.
    Returns an array with the same shape as arr.
    """
    # arr   : numpy array
    # kernel: 1D numpy array
    # axis  : int -> axis along which to convolve
    pad = kernel.size // 2
    pad_width = [(0, 0)] * arr.ndim
    pad_width[axis] = (pad, pad)
    arr_padded = np.pad(arr, pad_width=pad_width, mode='reflect')

    # Move target axis to front, convolve each line
    arr_move = np.moveaxis(arr_padded, axis, 0)
    rest_shape = arr_move.shape[1:]
    rest_size = int(np.prod(rest_shape)) if rest_shape else 1

    arr_lines = arr_move.reshape(arr_move.shape[0], rest_size)
    out_lines = np.empty((arr_move.shape[0] - 2 * pad, rest_size), dtype=arr.dtype)

    for j in range(rest_size):
        out_lines[:, j] = np.convolve(arr_lines[:, j], kernel, mode='valid')

    out_move = out_lines.reshape((arr.shape[axis],) + rest_shape)
    return np.moveaxis(out_move, 0, axis)


def _gaussian_blur2d(image, sigma, truncate=3.0):
    """
    Apply a separable 2D Gaussian blur with std=sigma to 'image' (μ=0).
    Uses reflect padding; returns same shape as input.
    """
    # image : (M,N) numpy array
    # sigma : float
    k = _gaussian_kernel1d(sigma, truncate=truncate)
    tmp = _convolve1d_reflect(image, k, axis=1)  # horizontal
    out = _convolve1d_reflect(tmp, k, axis=0)    # vertical
    return out


# ---------------------- Pipeline ----------------------

def initial_processing(
    I1,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Compute the log-intensity difference and cosine double-angle map.
    If I2 is None and sigma is provided, I2 is generated by convolving I1 with
    a 2D Gaussian (μ=0, σ=sigma along x & y).
    """
    # I1   : numpy array -> Intensity map I1
    # chi  : numpy array -> Angle map in radians (same shape as I1)
    # I2   : numpy array or None -> Optional intensity map I2
    # sigma: float or None -> std for Gaussian-blur to generate I2 when I2 is None

    if I2 is None and sigma is None:
        raise ValueError("Provide either I2 or sigma to generate I2 via Gaussian blur.")
    if I2 is not None and sigma is not None:
        raise ValueError("Provide exactly one of I2 or sigma, not both.")

    if sigma is not None:
        I2 = _gaussian_blur2d(I1, float(sigma))

    if I1.shape != I2.shape or I1.shape != chi.shape:
        raise ValueError("I1, I2, and chi must have identical shapes.")

    ln_I1 = np.log(I1)
    ln_I2 = np.log(I2)
    ln_delta_I = ln_I1 - ln_I2
    cos_2_chi = np.cos(2 * chi)
    return ln_delta_I, cos_2_chi


def get_m_and_g_constants(
    I1,
    q,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Global linear least-squares fit over ALL samples:
      y = G(q) + M(q) * x

    with t = q**2 and polynomial bases:
      G(q) = g0 + g1*t + g2*t**2 + g3*t**3
      M(q) = m1*t + m2*t**2 + m3*t**3

    Optional:
      Provide I2 directly OR provide sigma to generate I2 = GaussianBlur(I1, sigma).

    Returns:
      g0, g1, m1, m2
    """
    # I1 : numpy array -> Intensity map I1
    # q  : numpy array -> Radial q (same shape as I1)
    # chi: numpy array -> Angle chi (same shape as I1)
    # I2 : numpy array or None -> Optional intensity map I2
    # sigma : float or None -> Gaussian sigma when I2 is None

    if I1.shape != q.shape or I1.shape != chi.shape:
        raise ValueError("I1, q, and chi must have identical shapes.")

    y, x = initial_processing(I1, chi, I2=I2, sigma=sigma)  # y = ln(I1) - ln(I2), x = cos(2*chi)
    y = y.ravel()
    x = x.ravel()
    t = (q**2).ravel()

    valid = np.isfinite(y) & np.isfinite(x) & np.isfinite(t)
    y = y[valid]; x = x[valid]; t = t[valid]

    # Design matrix columns: [1, t, t^2, t^3, x*t, x*t^2, x*t^3]
    Phi_g = np.column_stack([np.ones_like(t), t, t**2, t**3])
    Phi_m = np.column_stack([t, t**2, t**3])
    Z = np.column_stack([Phi_g, x[:, None] * Phi_m])

    theta, _, _, _ = np.linalg.lstsq(Z, y, rcond=None)
    g0, g1, g2, g3, m1, m2, m3 = theta
    return float(g0), float(g1), float(m1), float(m2)


def get_V_and_phi_tagtag(
    I1,
    q,
    chi,
    *,
    r_g_sq_mod,
    I2=None,
    sigma=None
):
    """
    Compute (V, phi_tagtag) via polynomial maps over (c_g, c_m).

    Options (mutually exclusive):
      - Provide I2 directly (2D numpy array).
      - OR provide sigma (float): generates I2 = GaussianBlur(I1, sigma).
    """
    # I1         : numpy array -> Intensity map I1
    # q          : numpy array -> Radial q
    # chi        : numpy array -> Angle chi
    # r_g_sq_mod : float       -> Modified radius of gyration squared (positive)
    # I2         : numpy array or None
    # sigma      : float or None

    if r_g_sq_mod <= 0:
        raise ValueError("r_g_sq_mod must be positive.")
    if (I2 is None) == (sigma is None):
        raise ValueError("Provide exactly one of I2 or sigma.")

    # Fit constants (will generate I2 internally if sigma is given)
    g0, g1, m1, m2 = get_m_and_g_constants(I1, q, chi, I2=I2, sigma=sigma)

    # Dimensionless ratios (new definitions)
    c_g = g1 / (g0 * r_g_sq_mod)
    c_m = m2 / (m1 * r_g_sq_mod)

    # Evaluate calibrated polynomial maps
    V = V_fun(c_m, c_g)
    phi = phi_tag_tag_fun(c_m, c_g)

    return [(float(V), float(phi))]