import numpy as np
from find_V_and_phi_tag_tag import V_fun, phi_tag_tag_fun
from blur_func import gaussian_blur2d
from guinier_approximation import estimate_Rg

# our code uses three function, initial processing, where we get the data ready for analysis and make sure we got the
# correct format of data.
# get m anf g constant, where we get values of an initial fit of the data.
# and get v and phi_tag_tag, where we use the initial fit to get the necessary data.

def polar_transform(
    q_x,
    q_y
):
    """

    Args:
        q_x: a numpy 2D array of x value of q in SAXS mesurment
        q_y: a numpy 2D array of y value of q in SAXS mesurment

    Returns:
        q: a numpy 2D array of the MAGNITUDE of each q value in the SAXS image
        chi: a numpy 2D array of the angle of each q value in the SAXS image
    """
    q = np.sqrt(q_x^2+q_y^2)
    chi =np.atan2(q_y,q_x)
    return q,chi

def initial_processing(
    I1,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Args:
        I1: a numpy 2D array of intensity in a SAXS image
        chi: a numpy 2D array of the angle of each q value in the SAXS image

        * and we need one of two extra parameters
        I2: a numpy 2D array of a second intensity mesurment in a SAXS image with diffrent anisotropy parameters
        sigma: a scalar, we use it to convole I1 with a gaussian blur of stdv=sigma and use
        # that as our I2. assumed numpy.float

    Returns:
        ln_delta_I: a numpy 2D array of the values ln(I1/I2)
        cos_2_chi: a numpy 2D array of cos(2*chi)
    """

    """
    Compute the log-intensity difference and cosine double-angle map.
    If I2 is None and sigma is provided, I2 is generated by convolving I1 with
    a 2D Gaussian (μ=0, σ=sigma along x & y).

    IMPORTANT:
    We only take ln(I1/I2) where I1/I2 > 0. Invalid points are set to NaN
    so they can be masked out upstream.
    """
    # we first make sure we got relevant data
    if I2 is None and sigma is None:
        raise ValueError("Provide either I2 or sigma to generate I2 via Gaussian blur.")
    if I2 is not None and sigma is not None:
        raise ValueError("Provide exactly one of I2 or sigma, not both.")

    # if we get sigma instead of I2, we convole I1 to generate a relevant I2
    if sigma is not None:
        I2 = gaussian_blur2d(I1, float(sigma))

    # we can then make sure shape sizes are equal
    if I1.shape != I2.shape or I1.shape != chi.shape:
        raise ValueError("I1, I2, and chi must have identical shapes.")

    # Mask where the ratio is valid and finite
    # np.errstate suppresess two error messages. divide is divinding by 0, by ignoring we get "inf", a string,
    # as the value, while invalid is invalid operations like 0/0, by ignoring we get "nan", a string as well.
    # we ignore them because we are about to mask them anyway, and we don't need an explicit error message each time
    # it happens.
    with np.errstate(divide='ignore', invalid='ignore'):
        ratio = I1 / I2
    # we then create a boolean mask out all the data that isn't a finite numper or a positive number
    # (because ln of negative isn't defined)
    valid_ratio = np.isfinite(ratio) & (ratio > 0)

    # we prepear an output array of the dimensions of I1, filled with nan in each cell.
    ln_delta_I = np.full_like(I1, np.nan, dtype=float)
    # we calculate plug into ln_delta_I all values of log(I1/I2) where the mask applies.
    ln_delta_I[valid_ratio] = np.log(ratio[valid_ratio])
    # we calculate the cosine of 2*chi
    cos_2_chi = np.cos(2 * chi)
    return ln_delta_I, cos_2_chi


def get_m_and_g_constants(
    I1,
    q,
    chi,
    *,
    I2=None,
    sigma=None
):
    """
    Args:
        I1: a numpy 2D array of intensity in a SAXS image
        q: a numpy 2D array of the MAGNITUDE of each q value in the SAXS image
        chi: a numpy 2D array of the angle of each q value in the SAXS image

        * and we need one of two extra parameters
        I2: a numpy 2D array of a second intensity mesurment in a SAXS image with diffrent anisotropy parameters
        sigma: a scalar, we use it to convole I1 with a gaussian blur of stdv=sigma and use
        # that as our I2. assumed numpy.float

    Returns:
        coeff: the coeffients of a relevant polynomial fit, a list of floats.
    """

    """
    Global linear least-squares fit over ALL valid samples:
      y = G(q) + M(q) * x
    
    where y=ln(I1/I2) and x=cos(2*chi)

    with t = q**2 and polynomial bases:
      G(q) = g0 + g1*t + g2*t**2 + g3*t**3
      M(q) = m1*t + m2*t**2 + m3*t**3

    Optional:
      Provide I2 directly OR provide sigma to generate I2 = GaussianBlur(I1, sigma).

    Returns ALL coefficients:
      g0, g1, g2, g3, m1, m2, m3
    """

    # we raise an error if the arrays aren't of the same sizes.
    if I1.shape != q.shape or I1.shape != chi.shape:
        raise ValueError("I1, q, and chi must have identical shapes.")

    # we calculate relevant parameters for our fitting using intial processing, with the optional I2 or sigma

    ln_delta_I, cos_2_chi = initial_processing(I1, chi, I2=I2, sigma=sigma)

    # Build flattened arrays and mask out invalids: the least sqaure fit needs 1D arrays to work.
    # ravel takes the 2D arrays and put all rows one after the other.
    y = ln_delta_I.ravel()
    x = cos_2_chi.ravel()
    t = (q**2).ravel()

    # we make sure again that the values are finite. better safe then sorry.
    valid = np.isfinite(y) & np.isfinite(x) & np.isfinite(t)
    y = y[valid]; x = x[valid]; t = t[valid]

    # If nothing valid, fail clearly
    if y.size == 0:
        raise ValueError("No valid samples where I1/I2 > 0 to perform the fit.")

    # in numerical linear least squares we translate the minimization problem into a linear algebra question
    # with matrix multiplication. For more data read about how np.linalg.lstsq works. As such we need
    # to create the relevant matrix

    # Design matrix columns: [1, t, t^2, t^3, x*t, x*t^2, x*t^3]
    Phi_g = np.column_stack([np.ones_like(t), t, t**2, t**3])
    Phi_m = np.column_stack([t, t**2, t**3])
    Z = np.column_stack([Phi_g, x[:, None] * Phi_m])

    # calculate the least sqaure fit.
    theta, _, _, _ = np.linalg.lstsq(Z, y, rcond=None)
    g0, g1, g2, g3, m1, m2, m3 = theta
    return (float(g0), float(g1), float(g2), float(g3),
            float(m1), float(m2), float(m3))


def get_V_and_phi_tagtag(
    I1,
    q_x,
    q_y,
    q_min,
    q_max,
    *,
    I2=None,
    sigma=None
):

    """
    Args:
        I1: a numpy 2D array of intensity in a SAXS image
        q_x: a numpy 2D array of the of each q_x value in the SAXS image
        q_y: a numpy 2D array of the of each q_y value in the SAXS image
        q_min: minimal q value of a Guinier approximation
        q_max: maximal q value of a Guinier approximation

        * and we need one of two extra parameters
        I2: a numpy 2D array of a second intensity mesurment in a SAXS image with diffrent anisotropy parameters
        sigma: a scalar, we use it to convole I1 with a gaussian blur of stdv=sigma and use
        # that as our I2. assumed numpy.float

    Returns:
        values: a list of three value: Rg, V and phi_tag_tag
    """
    """
    Compute (V, phi_tagtag) via polynomial maps over two relevant floats (c_g, c_m).

    Options (mutually exclusive):
      - Provide I2 directly (2D numpy array).
      - OR provide sigma (float): generates I2 = GaussianBlur(I1, sigma).
    """

    # move to polar coordinates
    q, chi = polar_transform(q_x, q_y)

    # using Guininer aprproximation get r_g_sq_mod - the Rg value with the varience
    # we first flatten our q and I values into 1D.
    """r_g_sq_mod: a numpy float, the value of Rg^2(1+V) which is derived from guinner analysis of the data."""
    flat_q = q.flatten()
    flat_I1 = I1.flatten()
    r_g_sq_mod = estimate_Rg(flat_q, flat_I1, q_min, q_max)^2

    # raise rlevant errors
    if r_g_sq_mod <= 0:
        raise ValueError("r_g_sq_mod must be positive.")
    if (I2 is None) == (sigma is None):
        raise ValueError("Provide exactly one of I2 or sigma.")

    # Fit coefficients (handles I2 generation & masking internally)
    g0, g1, g2, g3, m1, m2, m3 = get_m_and_g_constants(I1, q, chi, I2=I2, sigma=sigma)

    # Use the right coefficients for c_g and c_m
    c_g = g1 / (g0 * r_g_sq_mod)
    c_m = m2 / (m1 * r_g_sq_mod)

    # derive the correct Rg, V and phi_tag_tag using the helper polynomial fit we wrote.
    V = V_fun(c_m, c_g)
    # raise rlevant error
    if V <= 0:
        raise ValueError("V came out negative.")
    phi_tag_tag = phi_tag_tag_fun(c_m, c_g)
    r_g = np.sqrt(r_g_sq_mod/(1+V))

    return [(float (r_g), float(V), float(phi_tag_tag))]